language: php

matrix:
    include:
        - php: 7.1
          env: SYMFONY_VERSION=~4.0
        - php: 7.2
          env: SYMFONY_VERSION=~4.0
        - php: 7.3
          env: SYMFONY_VERSION=~4.0

before_install:
    - if [ $stability != "" ]; then composer config minimum-stability $stability; fi

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION;
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php build/coverage-checker.php build/clover.xml 70; fi
    - ./vendor/bin/phpcs --standard=PSR2 ./lib/ ./tests/OnurbTest/

after_script:
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml; fi
